### ISSUE TITLE
Raise `unknown keywords: fg_color (ArgumentError)` with Reline 0.3.1

### ISSUE THREAD

**Issue by ybiquitous** [tompng/katakata_irb#8]
Hi, thanks for the great talk at RubyKaigi 2023!

I encountered the following error in a specific environment when I was playing this gem:

```console
irb(main):001:0> 1.bundler: failed to load command: irb (/usr/local/bundle/bin/irb)
/usr/local/bundle/gems/katakata_irb-0.1.8/lib/katakata_irb/completor.rb:133:in `initialize': unknown keywords: fg_color (ArgumentError)         1.__send__                       ▀
                 1.abs
      Reline::DialogRenderInfo.new(pos: Reline::CursorPos.new(x, y), contents: contents, width: width, bg_color: 44, fg_color: 37)              1.allbits?
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^               1.anybits?
	from /usr/local/bundle/gems/katakata_irb-0.1.8/lib/katakata_irb/completor.rb:133:in `new'
	from /usr/local/bundle/gems/katakata_irb-0.1.8/lib/katakata_irb/completor.rb:133:in `block in setup_type_dialog'
	from /usr/local/bundle/gems/reline-0.3.1/lib/reline/line_editor.rb:588:in `instance_exec'
	from /usr/local/bundle/gems/reline-0.3.1/lib/reline/line_editor.rb:588:in `call'
	from /usr/local/bundle/gems/reline-0.3.1/lib/reline/line_editor.rb:623:in `call'
	from /usr/local/bundle/gems/reline-0.3.1/lib/reline/line_editor.rb:667:in `render_each_dialog'
	from /usr/local/bundle/gems/reline-0.3.1/lib/reline/line_editor.rb:651:in `block in render_dialog'
	from /usr/local/bundle/gems/reline-0.3.1/lib/reline/line_editor.rb:650:in `each'
	from /usr/local/bundle/gems/reline-0.3.1/lib/reline/line_editor.rb:650:in `render_dialog'
	from /usr/local/bundle/gems/reline-0.3.1/lib/reline/line_editor.rb:510:in `rerender'
	from /usr/local/bundle/gems/reline-0.3.1/lib/reline.rb:330:in `block (3 levels) in inner_readline'
	from /usr/local/bundle/gems/reline-0.3.1/lib/reline.rb:328:in `each'
	from /usr/local/bundle/gems/reline-0.3.1/lib/reline.rb:328:in `block (2 levels) in inner_readline'
	from /usr/local/bundle/gems/reline-0.3.1/lib/reline.rb:403:in `block in read_io'
	from /usr/local/bundle/gems/reline-0.3.1/lib/reline.rb:373:in `loop'
	from /usr/local/bundle/gems/reline-0.3.1/lib/reline.rb:373:in `read_io'
	from /usr/local/bundle/gems/reline-0.3.1/lib/reline.rb:326:in `block in inner_readline'
	from /usr/local/bundle/gems/reline-0.3.1/lib/reline.rb:324:in `loop'
	from /usr/local/bundle/gems/reline-0.3.1/lib/reline.rb:324:in `inner_readline'
	from /usr/local/bundle/gems/reline-0.3.1/lib/reline.rb:254:in `readmultiline'
	from /usr/local/lib/ruby/3.2.0/forwardable.rb:240:in `readmultiline'
	from /usr/local/lib/ruby/3.2.0/forwardable.rb:240:in `readmultiline'
	from /usr/local/bundle/gems/irb-1.6.4/lib/irb/input-method.rb:417:in `gets'
	from /usr/local/bundle/gems/irb-1.6.4/lib/irb.rb:542:in `block (2 levels) in eval_input'
	from /usr/local/bundle/gems/irb-1.6.4/lib/irb.rb:770:in `signal_status'
	from /usr/local/bundle/gems/irb-1.6.4/lib/irb.rb:541:in `block in eval_input'
	from /usr/local/bundle/gems/irb-1.6.4/lib/irb/ruby-lex.rb:269:in `lex'
	from /usr/local/bundle/gems/irb-1.6.4/lib/irb/ruby-lex.rb:238:in `block (2 levels) in each_top_level_statement'
	from /usr/local/bundle/gems/irb-1.6.4/lib/irb/ruby-lex.rb:235:in `loop'
	from /usr/local/bundle/gems/irb-1.6.4/lib/irb/ruby-lex.rb:235:in `block in each_top_level_statement'
	from /usr/local/bundle/gems/irb-1.6.4/lib/irb/ruby-lex.rb:234:in `catch'
	from /usr/local/bundle/gems/irb-1.6.4/lib/irb/ruby-lex.rb:234:in `each_top_level_statement'
	from /usr/local/bundle/gems/irb-1.6.4/lib/irb.rb:560:in `eval_input'
	from /usr/local/bundle/gems/irb-1.6.4/lib/irb.rb:494:in `block in run'
	from /usr/local/bundle/gems/irb-1.6.4/lib/irb.rb:493:in `catch'
	from /usr/local/bundle/gems/irb-1.6.4/lib/irb.rb:493:in `run'
	from /usr/local/bundle/gems/irb-1.6.4/lib/irb.rb:416:in `start'
	from /usr/local/bundle/gems/irb-1.6.4/exe/irb:9:in `<top (required)>'
	from /usr/local/bundle/bin/irb:25:in `load'
	from /usr/local/bundle/bin/irb:25:in `<top (required)>'
	from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
	from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
	from /usr/local/lib/ruby/3.2.0/bundler/cli.rb:492:in `exec'
	from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
	from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/libexec/bundle:45:in `block in <top (required)>'
	from /usr/local/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/libexec/bundle:33:in `<top (required)>'
	from /usr/local/bin/bundle:25:in `load'
	from /usr/local/bin/bundle:25:in `<main>'
```

`Gemfile`:

```ruby
source 'https://rubygems.org'
ruby '3.2.2'
gem 'katakata_irb', '0.1.8'
gem 'irb', '1.6.4'
gem 'reline', '0.3.1'
```

Reproduction steps:

1. Run `bundle install`
2. Run `bundle exec irb -r katakata_irb`
3. Type `1.` , and then get the `ArgumentError` above

This error never occurs with Reline 0.3.2.

**Comment by tompng** [comment]
Thanks for the report 👍 
I'll release a new version after some other fixes

**Comment by ybiquitous** [comment]
I'd like to say "thank you" for this cool gem. I'm looking forward to the next update!
